#### Good Morning All
## Numpy --> it is a package
* numerical python
* it is used to process the single and multi-dimentional array
    - array is collection homogeneous data
    - []
* 2005

In [2]:
l = [1,2,3,4,5,6] #--> one array 
#l
print(type(l))

<class 'list'>


In [37]:
#sigle dim array ==> [1,2,3,4,5]
import numpy as np
l = [1,2,3,4,5]
l1 = np.array(l)
print(type(l1))
print(l1)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [11]:
n = [1,2,3,4,5]
n1 = [2,3,4,5,6]
np.array([n,n1])

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [14]:
ar = list(map(int,input().split()))
np.array(ar)

1 2 3 4 5


array([1, 2, 3, 4, 5])

In [15]:
np.array([[1,2,3,4],[3,4,5,6],[6,7,8,9]])

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [6, 7, 8, 9]])

In [17]:
list_ = input().split()
list_

1.5 4.5 40 abc


['1.5', '4.5', '40', 'abc']

In [19]:
list2 = input().split()
res = list(map(int,list2))
np.array(res)

1 2 3 4 5 6


array([1, 2, 3, 4, 5, 6])

In [ ]:
np.array([[1,2,3,4],[3,4,5,6],[6,7,8,9]])

In [50]:
l1 = list(map(int,input().split()))
l2 = list(map(int,input().split()))
l3 = list(map(int,input().split()))
np.array([l1,l2,l3])

1 2 3 4 5 6
6 45 4 3 5 78
89 56 43 2 1 67


array([[ 1,  2,  3,  4,  5,  6],
       [ 6, 45,  4,  3,  5, 78],
       [89, 56, 43,  2,  1, 67]])

In [21]:
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [22]:
n = np.arange(1,50)
n.reshape([7,7])

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [23]:
n.reshape([6,7])

ValueError: cannot reshape array of size 49 into shape (6,7)

In [24]:
n1 = np.arange(1,43)
n1.reshape([6,7])

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42]])

In [25]:
n1 = np.arange(1,43)
n1.reshape([7,7])

ValueError: cannot reshape array of size 42 into shape (7,7)

In [26]:
random = np.random.randint(1,50,size=[6,7])
random

array([[22, 12,  7, 22, 46, 38, 13],
       [39, 17, 38, 28,  1, 38,  7],
       [ 1, 16,  7, 15, 35, 24,  6],
       [13, 48, 45, 10, 25, 30, 17],
       [21,  9, 15, 18, 49, 38,  4],
       [42, 20, 32, 11, 44, 23, 38]])

In [27]:
random1 = np.random.randint(1,50,size=[7,7])
random1

array([[43, 45,  5, 36, 12,  6, 25],
       [16, 39, 32, 16, 39,  2, 14],
       [30, 39, 48, 13, 12,  4, 13],
       [45, 23, 17, 23, 24, 28, 14],
       [20, 13, 22, 17, 46, 39,  4],
       [ 5, 30, 18, 49, 28, 42, 12],
       [36, 20, 20, 41, 23, 23, 13]])

In [28]:
random2 = np.random.randint(1,50,size=[10,5])
random2

array([[21, 36, 37, 11, 21],
       [36, 18, 19, 26, 48],
       [ 1, 28, 32, 36,  3],
       [30, 48, 21, 41,  2],
       [33, 36, 36, 49, 31],
       [ 7,  1, 14, 44, 29],
       [27, 18, 29,  2, 37],
       [ 1, 15, 44, 14,  2],
       [ 6,  1, 43, 29, 14],
       [30, 35, 19, 48,  2]])

In [35]:
random.shape

(6, 7)

In [36]:
random.reshape([7,6])

array([[22, 12,  7, 22, 46, 38],
       [13, 39, 17, 38, 28,  1],
       [38,  7,  1, 16,  7, 15],
       [35, 24,  6, 13, 48, 45],
       [10, 25, 30, 17, 21,  9],
       [15, 18, 49, 38,  4, 42],
       [20, 32, 11, 44, 23, 38]])

In [30]:
random.size

42

In [32]:
random.max()

49

In [33]:
random.min()

1

In [34]:
random.sum()

984

In [39]:
random.mean()

23.428571428571427

In [40]:
random.std()

14.056252391463275

In [41]:
mt1 = np.random.randint(1,40,size=[3,4])
mt2 = np.random.randint(45,100,size=[3,4])


In [44]:
print(mt1+mt2)

[[ 66 119  95  75]
 [ 98 127  85  86]
 [ 73 121 107 119]]


In [45]:
print(mt1-mt2)

[[-54 -71 -27 -21]
 [-44 -63  -9 -48]
 [-23 -67 -85 -65]]


In [46]:
print(mt1*mt2)

[[ 360 2280 2074 1296]
 [1917 3040 1786 1273]
 [1200 2538 1056 2484]]


In [47]:
print(mt1/mt2)

[[0.1        0.25263158 0.55737705 0.5625    ]
 [0.38028169 0.33684211 0.80851064 0.28358209]
 [0.52083333 0.28723404 0.11458333 0.29347826]]


In [48]:
print(mt1//mt2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [49]:
print(mt1**4)

[[   1296  331776 1336336  531441]
 [ 531441 1048576 2085136  130321]
 [ 390625  531441   14641  531441]]


#### built in function in numpy
1. ones
2. zeros
3. vstack
4. hstack

In [51]:
random

array([[22, 12,  7, 22, 46, 38, 13],
       [39, 17, 38, 28,  1, 38,  7],
       [ 1, 16,  7, 15, 35, 24,  6],
       [13, 48, 45, 10, 25, 30, 17],
       [21,  9, 15, 18, 49, 38,  4],
       [42, 20, 32, 11, 44, 23, 38]])

In [53]:
print(random1)
print(random1.shape)

[[43 45  5 36 12  6 25]
 [16 39 32 16 39  2 14]
 [30 39 48 13 12  4 13]
 [45 23 17 23 24 28 14]
 [20 13 22 17 46 39  4]
 [ 5 30 18 49 28 42 12]
 [36 20 20 41 23 23 13]]
(7, 7)


In [54]:
unit = np.ones((3,3))
unit

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [55]:
unit = np.ones((3,3),int)
unit

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [56]:
null = np.zeros((4,4))
null

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
null = np.zeros((4,4),int)
null

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [58]:
null

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [59]:
vstack_ex = np.vstack([null,null+5])
vstack_ex

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [61]:
hstack_ex = np.hstack([null,null-1])
hstack_ex

array([[ 0,  0,  0,  0, -1, -1, -1, -1],
       [ 0,  0,  0,  0, -1, -1, -1, -1],
       [ 0,  0,  0,  0, -1, -1, -1, -1],
       [ 0,  0,  0,  0, -1, -1, -1, -1]])

In [ ]:
[1 0 0
 0 1 0
 0 0 1] --> diagnal matrix

In [66]:
#daignal matrix
daignal = np.zeros((3,3),int)
np.diag([1,1,1])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [69]:
print(random)
random.shape

[[22 12  7 22 46 38 13]
 [39 17 38 28  1 38  7]
 [ 1 16  7 15 35 24  6]
 [13 48 45 10 25 30 17]
 [21  9 15 18 49 38  4]
 [42 20 32 11 44 23 38]]


(6, 7)

In [70]:
random.T

array([[22, 39,  1, 13, 21, 42],
       [12, 17, 16, 48,  9, 20],
       [ 7, 38,  7, 45, 15, 32],
       [22, 28, 15, 10, 18, 11],
       [46,  1, 35, 25, 49, 44],
       [38, 38, 24, 30, 38, 23],
       [13,  7,  6, 17,  4, 38]])

In [71]:
random.transpose()

array([[22, 39,  1, 13, 21, 42],
       [12, 17, 16, 48,  9, 20],
       [ 7, 38,  7, 45, 15, 32],
       [22, 28, 15, 10, 18, 11],
       [46,  1, 35, 25, 49, 44],
       [38, 38, 24, 30, 38, 23],
       [13,  7,  6, 17,  4, 38]])

In [77]:
from numpy.linalg import inv

In [78]:
inv_ex = np.array([[1,2],[3,4]])
inv_ex

array([[1, 2],
       [3, 4]])

In [79]:
res = inv(inv_ex)
res

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [80]:
ex2 = np.random.randint(1,50,size = (7,7))
ex2

array([[18, 31, 34, 35,  7, 31,  6],
       [46, 18, 33, 12, 48, 43, 39],
       [43, 40, 32, 47, 13,  5,  6],
       [42, 48, 24, 45, 49, 47, 47],
       [ 4, 44, 10,  8, 40, 42, 18],
       [22, 27, 48, 20, 12, 37, 43],
       [32, 27, 17, 22, 33, 41, 38]])

In [81]:
inv_ex2 = inv(ex2)
inv_ex2

array([[-0.01168648, -0.00228971,  0.03077038, -0.05900192,  0.00038737,
        -0.01132618,  0.08494575],
       [-0.02664564, -0.0238936 ,  0.03273076, -0.04005965,  0.02991789,
         0.01068635,  0.04684496],
       [ 0.00780285,  0.02272969, -0.00504052,  0.01683335,  0.00025781,
         0.0173607 , -0.06435133],
       [ 0.02739981,  0.00040896, -0.02451282,  0.06175379, -0.02528443,
        -0.00974138, -0.05425529],
       [ 0.00249982,  0.03206959, -0.01813739,  0.05708222,  0.00103277,
        -0.00754765, -0.09299457],
       [ 0.03062378, -0.00463151, -0.01265619, -0.03021972, -0.00072258,
        -0.01476467,  0.05634309],
       [-0.02579246, -0.01435286, -0.00331512,  0.01790044, -0.0071779 ,
         0.02230286,  0.00166488]])